import type { CurriculumGoal } from "@/types";

/**
 * Kleine, direct bruikbare seed met publiek verifieerbare doelen. Dit is geen
 * volledige kopie van de leerplandatabanken. Elke record bewaart zijn bron en
 * geldigheid; beveiligde OVSG/ZILL-platformen worden bewust niet gespiegeld.
 */
export const curriculumData: CurriculumGoal[] = [
  {
    id: "vl-lo-et-mm-3.7",
    source: "minimumdoel",
    network: "VLAANDEREN",
    code: "MM 3.7",
    text: "De leerlingen kunnen hun afstamming aangeven tot twee generaties terug.",
    domain: "Mens en maatschappij · Tijd",
    subject: "Historische tijd",
    schoolYears: ["2025-2026", "2026-2027"],
    status: "active",
    sourceUrl: "https://www.onderwijsdoelen.be/",
    retrievedAt: "2026-08-26",
    version: "LO 1.0",
    approvalStatus: "geldend eindtermenkader",
    keywords: ["afstamming", "generaties", "familie", "verleden", "tijd"],
  },
  {
    id: "vl-lo-et-mm-3.8",
    source: "minimumdoel",
    network: "VLAANDEREN",
    code: "MM 3.8",
    text: "De leerlingen kunnen aan de hand van een tijdlijn belangrijke gebeurtenissen of personen uit hun omgeving in de juiste tijdsperiode situeren.",
    domain: "Mens en maatschappij · Tijd",
    subject: "Historisch referentiekader",
    schoolYears: ["2025-2026", "2026-2027"],
    status: "active",
    sourceUrl: "https://www.onderwijsdoelen.be/",
    retrievedAt: "2026-08-26",
    version: "LO 1.0",
    approvalStatus: "geldend eindtermenkader",
    keywords: ["tijdlijn", "situeren", "gebeurtenissen", "personen", "historisch"],
  },
  {
    id: "vl-lo-et-wi-1.4",
    source: "minimumdoel",
    network: "VLAANDEREN",
    code: "WI 1.4",
    text: "De leerlingen kunnen in voorbeelden herkennen dat breuken gelijkwaardig kunnen zijn en kunnen gelijkwaardige breuken noteren.",
    domain: "Wiskunde · Getallen",
    subject: "Breuken",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl: "https://www.onderwijsdoelen.be/",
    retrievedAt: "2026-08-26",
    version: "LO 1.0",
    approvalStatus: "geldend eindtermenkader",
    keywords: ["breuken", "gelijkwaardig", "noteren", "teller", "noemer"],
  },
  {
    id: "vl-lo-et-nl-1.5",
    source: "minimumdoel",
    network: "VLAANDEREN",
    code: "NL 1.5",
    text: "De leerlingen kunnen de informatie op een persoonlijke en overzichtelijke wijze ordenen bij een voor hen bestemde instructie.",
    domain: "Nederlands · Luisteren",
    subject: "Informatie verwerken",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl: "https://www.onderwijsdoelen.be/",
    retrievedAt: "2026-08-26",
    version: "LO 1.0",
    approvalStatus: "geldend eindtermenkader",
    keywords: ["luisteren", "informatie", "ordenen", "instructie", "overzicht"],
  },
  {
    id: "vl-lo-et-wt-1.2",
    source: "minimumdoel",
    network: "VLAANDEREN",
    code: "WT 1.2",
    text: "De leerlingen kunnen gericht waarnemen met alle zintuigen en kunnen waarnemingen op een systematische wijze noteren.",
    domain: "Wetenschappen en techniek · Natuur",
    subject: "Onderzoeken",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl: "https://www.onderwijsdoelen.be/",
    retrievedAt: "2026-08-26",
    version: "LO 1.0",
    approvalStatus: "geldend eindtermenkader",
    keywords: ["waarnemen", "zintuigen", "onderzoeken", "noteren", "natuur"],
  },
  {
    id: "vl-lo-v2-toekomst",
    source: "minimumdoel",
    network: "VLAANDEREN",
    code: "LO 2.0 · toekomstige set",
    text: "Nieuwe minimumdoelen basisonderwijs: alleen beschikbaar via de toekomstindex tot de toepassingsregels voor schooljaar, leerjaar en discipline voldaan zijn.",
    domain: "Overgang nieuwe minimumdoelen",
    subject: "Toekomstige doelen",
    schoolYears: ["2026-2027", "2027-2028"],
    status: "future",
    sourceUrl:
      "https://www.vlaanderen.be/onderwijsprofessionals/lesgeven-en-begeleiden/opleidingsinhouden/opleidingsinhouden-basisonderwijs/nieuwe-minimumdoelen-basisonderwijs",
    retrievedAt: "2026-08-26",
    version: "LO 2.0",
    approvalStatus: "gefaseerde invoering",
    keywords: ["nieuwe minimumdoelen", "toekomst", "invoering"],
  },
  {
    id: "zill-owti1",
    source: "leerplandoel",
    network: "ZILL",
    code: "OWti1",
    text: "Zich bewust worden van de persoonlijke en culturele beleving van tijd.",
    domain: "Ontwikkeling van oriëntatie op de wereld",
    subject: "Oriëntatie op tijd",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl: "https://zill.katholiekonderwijs.vlaanderen/",
    retrievedAt: "2026-08-26",
    version: "ZILL 2018",
    approvalStatus: "goedgekeurd leerplan",
    keywords: ["tijd", "beleving", "persoonlijk", "cultureel", "verleden"],
  },
  {
    id: "zill-owti2",
    source: "leerplandoel",
    network: "ZILL",
    code: "OWti2",
    text: "Tijdsbegrippen en verschillende soorten kalenders functioneel gebruiken.",
    domain: "Ontwikkeling van oriëntatie op de wereld",
    subject: "Oriëntatie op tijd",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl: "https://zill.katholiekonderwijs.vlaanderen/",
    retrievedAt: "2026-08-26",
    version: "ZILL 2018",
    approvalStatus: "goedgekeurd leerplan",
    keywords: ["tijdsbegrippen", "kalender", "chronologie", "dag", "jaar"],
  },
  {
    id: "zill-owti3",
    source: "leerplandoel",
    network: "ZILL",
    code: "OWti3",
    text: "Gebeurtenissen uit het eigen leven en uit de geschiedenis verkennen en in de tijd situeren.",
    domain: "Ontwikkeling van oriëntatie op de wereld",
    subject: "Oriëntatie op tijd",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl: "https://zill.katholiekonderwijs.vlaanderen/",
    retrievedAt: "2026-08-26",
    version: "ZILL 2018",
    approvalStatus: "goedgekeurd leerplan",
    keywords: ["geschiedenis", "gebeurtenissen", "situeren", "tijdlijn", "romeinen"],
  },
  {
    id: "zill-tomn2",
    source: "leerplandoel",
    network: "ZILL",
    code: "TOmn2",
    text: "Een mondelinge boodschap overbrengen.",
    domain: "Taalontwikkeling",
    subject: "Mondelinge taalvaardigheid",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl: "https://zill.katholiekonderwijs.vlaanderen/",
    retrievedAt: "2026-08-26",
    version: "ZILL 2018",
    approvalStatus: "goedgekeurd leerplan",
    keywords: ["spreken", "boodschap", "mondeling", "presenteren", "vertellen"],
  },
  {
    id: "ovsg-ll-publiek-geschiedenis",
    source: "leerplandoel",
    network: "OVSG",
    code: "LeerLokaal · basisleerlijn geschiedenis",
    text: "Leerlingen bouwen kennis op over het verleden en over historische gebeurtenissen en bouwen aan een historisch referentiekader.",
    domain: "Ik en de wereld",
    subject: "Kennis van het verleden",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl:
      "https://www.ovsg.be/onze-themas/leerplannen-didactiek/basisonderwijs/leer-lokaal/leergebieden-leerlijnen-leerlokaal",
    retrievedAt: "2026-08-26",
    version: "LeerLokaal 2023-2026",
    approvalStatus: "publiek verifieerbare leerplanbeschrijving; doelcode-export vereist",
    keywords: ["geschiedenis", "verleden", "historische gebeurtenissen", "referentiekader"],
  },
  {
    id: "ovsg-ll-publiek-bronnen",
    source: "leerplandoel",
    network: "OVSG",
    code: "LeerLokaal · leerlijn historische kennis",
    text: "Leerlingen stellen historische vragen en werken met diverse bronnenmaterialen om een antwoord te formuleren.",
    domain: "Ik en de wereld",
    subject: "Historische kennis en bronnen",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl:
      "https://www.ovsg.be/volumes/general/Leerplannen-en-didactiek/Lager-onderwijs/260130-Visie-De-wereld-ik.pdf",
    retrievedAt: "2026-08-26",
    version: "LeerLokaal 2023-2026",
    approvalStatus: "publiek verifieerbare visie; doelcode-export vereist",
    keywords: ["historische vragen", "bronnen", "onderzoeken", "vergelijken", "kritisch"],
  },
  {
    id: "ovsg-ll-publiek-spiraal",
    source: "leerplandoel",
    network: "OVSG",
    code: "LeerLokaal · basisleerlijn",
    text: "Leerlingen verbinden nieuwe kennis systematisch met eerder verworven kennis binnen een doorlopende leerlijn.",
    domain: "LeerLokaal",
    subject: "Kenniscreatie",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl:
      "https://www.ovsg.be/nieuws/leer-lokaal-schiet-uit-de-startblokken",
    retrievedAt: "2026-08-26",
    version: "LeerLokaal 2023-2026",
    approvalStatus: "publiek verifieerbare leerplanbeschrijving; doelcode-export vereist",
    keywords: ["kennis", "verbinden", "spiraalcurriculum", "leerlijn"],
  },
  {
    id: "ovsg-update-future",
    source: "leerplandoel",
    network: "OVSG",
    code: "LeerLokaal update",
    text: "Geactualiseerde LeerLokaal-leerlijnen bij de nieuwe minimumdoelen.",
    domain: "LeerLokaal update",
    subject: "Toekomstige editie",
    schoolYears: ["2026-2027"],
    status: "future",
    sourceUrl:
      "https://www.ovsg.be/onze-themas/leerplannen-didactiek/basisonderwijs/leer-lokaal/leerplan-leer-lokaal",
    retrievedAt: "2026-08-26",
    version: "Update 2026",
    approvalStatus: "tijdelijk goedgekeurd; niet actief in 2025-2026",
    keywords: ["update", "toekomst", "minimumdoelen"],
  },
  {
    id: "go-media-7.2",
    source: "leerplandoel",
    network: "GO",
    code: "7.2 · Media begrijpen",
    text: "De leerlingen herkennen media als middelen om boodschappen over te brengen en informatie te verwerven.",
    domain: "Media",
    subject: "Media begrijpen",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl:
      "https://pro.g-o.be/download/GOPRO-1830562155-6235/Leerplan%20media%20-%20pdf",
    retrievedAt: "2026-08-26",
    version: "GO! leerplan media",
    approvalStatus: "gepubliceerd leerplan",
    keywords: ["media", "boodschap", "informatie", "begrijpen", "communicatie"],
  },
  {
    id: "go-media-7.3.6",
    source: "leerplandoel",
    network: "GO",
    code: "7.3.6",
    text: "De leerlingen kunnen bij realistische rekenopdrachten media inzetten om informatie op te zoeken, te verwerken en te presenteren.",
    domain: "Media",
    subject: "Media gebruiken",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl:
      "https://pro.g-o.be/download/GOPRO-1830562155-6235/Leerplan%20media%20-%20pdf",
    retrievedAt: "2026-08-26",
    version: "GO! leerplan media",
    approvalStatus: "gepubliceerd leerplan",
    keywords: ["media", "rekenen", "informatie", "opzoeken", "presenteren"],
  },
  {
    id: "go-lo-6.2.1.10",
    source: "leerplandoel",
    network: "GO",
    code: "6.2.1.10",
    text: "De leerlingen voeren eenvoudige bewegingsopdrachten doelgericht, veilig en met controle uit.",
    domain: "Lichamelijke opvoeding",
    subject: "Motorische competenties",
    schoolYears: ["2025-2026"],
    status: "active",
    sourceUrl:
      "https://pro.g-o.be/download/GOPRO-1830562155-5028/PDF%20-%20Leerplan%20lichamelijke%20opvoeding%20basisonderwijs%20kleuteronderwijs%20en%20lager%20onderwijs",
    retrievedAt: "2026-08-26",
    version: "GO! leerplan lichamelijke opvoeding",
    approvalStatus: "gepubliceerd leerplan",
    keywords: ["bewegen", "motorisch", "veilig", "controle", "uitvoeren"],
  },
  {
    id: "go-new-future",
    source: "leerplandoel",
    network: "GO",
    code: "GO! kennisrijk leerplan BaO",
    text: "Nieuwe kennisrijke doelensets voor het basisonderwijs.",
    domain: "Nieuw leerplan basisonderwijs",
    subject: "Toekomstige editie",
    schoolYears: ["2026-2027"],
    status: "future",
    sourceUrl:
      "https://pro.g-o.be/themas/leerplannen/basisonderwijs/nieuw-leerplan-basisonderwijs/",
    retrievedAt: "2026-08-26",
    version: "voorlopige versie 2026",
    approvalStatus: "future/quarantaine; formele toepassing controleren",
    keywords: ["nieuw leerplan", "kennisrijk", "toekomst"],
  },
];
