import Link from "next/link";
import { analyticsConfiguration } from "@/lib/analytics/config";
export default function PrivacyPage() {
  const analytics = analyticsConfiguration();
  return <main className="mx-auto max-w-3xl space-y-6 px-6 py-10 text-sm leading-7">
    <Link href="/" className="underline">Terug naar de app</Link>
    <h1 className="text-3xl font-bold">Privacy en cookies</h1>
    <p>Actuele uitleg voor alle gebruikers · 19 september 2026. Generative Labs verwerkt gegevens om Leerkrachtentools te leveren. Je akkoord met de <Link href="/voorwaarden?versie=2026-09-13" className="underline">gebruiksvoorwaarden</Link> en je optionele keuze voor statistieken zijn afzonderlijk.</p>
    <h2 className="text-xl font-semibold">Lesinhoud, bestanden en AI</h2>
    <p>Lesopslag gebeurt hoofdzakelijk in je browser. Dat sluit verwerking elders niet uit: uploads en bestandsnamen gaan naar onze server voor het lezen van documenten; AI-functies sturen de noodzakelijke tekst en waar nodig bestanden, audio en bestandsnamen naar de ingestelde dienst. Bij Word-export verwerkt onze server het document en de geselecteerde lesgegevens. Voer geen identificeerbare leerlinggegevens in.</p>
    <p>De Google-koppeling gebruikt de Gemini API, niet Vertex AI. De code ondersteunt daarnaast Groq, Cerebras, SambaNova en Cloudflare, afhankelijk van de ingestelde sleutels en eigen accountinstellingen; sommige functies kunnen een beschikbare fallback gebruiken. Welke daarvan in een werkelijk draaiende omgeving actief zijn, is nog niet bevestigd. Optioneel kan Google Discovery Engine zoektermen en corpusfragmenten verwerken; die afzonderlijke zoekdienst is geen Vertex AI-migratie van de Gemini-koppeling. Brevo verwerkt e-mailadressen en berichten voor inlogcodes en feedback als e-mail is geconfigureerd. Generative Labs gebruikt klantinhoud niet om eigen modellen te trainen. Verwerking door leveranciers volgt hun toepasselijke voorwaarden. Er is geen garantie van uitsluitend Europese verwerking.</p>
    <h2 className="text-xl font-semibold">Noodzakelijke registratie en bewaring</h2>
    <p>Voor toegang bewaren we accountgegevens, beveiligde inloggegevens en het bewijs van de geaccepteerde voorwaardenversie. Sessies verlopen na maximaal zeven dagen of 24 uur inactiviteit. Inlogcodes zijn tien minuten geldig; records kunnen tot de opruiming na 24 uur blijven bestaan om misbruikcontroles te beschermen. Technische foutlogs bevatten alleen toegestane foutcategorieën en codes, geen lesinhoud of authenticatiegegevens.</p>
    <p>De code gebruikt 48 uur voor korte gebruiks- en misbruikregistratie, zeven dagen voor dagtellers en 90 dagen voor API-, feedback- en beveiligingsregistratie. B2B-antwoorden kunnen maximaal 24 uur beschikbaar zijn voor veilige herhaling van een verzoek; lopende verzoeken worden bij opruiming beschermd. Quotaledgers en akkoordbewijs hebben een afzonderlijk doel en worden niet met deze tijdelijke records gewist. Dit zijn coderegels: actieve opruiming, serverlogs, back-ups, hostingregio en werkelijk ingestelde bewaartermijnen moeten vóór ingebruikname nog worden gecontroleerd.</p>
    <h2 className="text-xl font-semibold">Optionele PostHog-statistieken</h2>
    <p>Via ‘Privacy &amp; cookies’ kun je even eenvoudig toestaan, weigeren of later intrekken. Zonder toestemming worden geen analytics-verzoeken verstuurd of events gebufferd. We meten alleen toegestane apppagina’s en het starten, slagen of mislukken van functies, met een tijdelijk willekeurig kenmerk in het geheugen. Geen identificatie met je account, formulieropname, session replay, lesinhoud, bestandsnamen, e-mailadressen of URL-parameters. Zoals bij elk netwerkverzoek kan de ontvangende dienst je IP-adres zien; locatieverrijking wordt uitgeschakeld.</p>
    <p>Je keuze wordt maximaal 180 dagen in dit browserprofiel onthouden. Bij gewijzigde configuratie, uitloggen of wisselen van account is opnieuw een keuze nodig. Weigeren blokkeert geen lesfunctie. Noodzakelijke sessiebeveiliging, quota en de opslag van deze keuze staan los van analytics. {analytics.ready ? `Volgens de bevestigde projectconfiguratie: PostHog-regio ${analytics.region}, eventretentie ${analytics.retentionMonths} maanden. De verwerkersovereenkomst is door de beheerder bevestigd.` : "De PostHog-projectregio, verwerkersovereenkomst en bewaartermijn zijn nog niet alle bevestigd: ONBEKEND. Analytics blijft uit tot deze zijn bevestigd."}</p>
    <h2 className="text-xl font-semibold">Inzage en afsluiten</h2>
    <p>In accountinstellingen kun je je accountgegevens exporteren en afzonderlijk je account verwijderen. Lesgegevens in je browser exporteer je via de lesfuncties. Organisaties kunnen een afgeschermde export en afsluiting aanvragen bij Generative Labs. Een export bevat geen sleutels, sessies of gegevens van anderen. Voor verzoeken over inzage, correctie of verwijdering: <a className="underline" href="https://www.generativelabs.be/juridisch.html">de contactgegevens van Generative Labs</a>. Je kunt een klacht indienen bij de <a className="underline" href="https://www.gegevensbeschermingsautoriteit.be/">Gegevensbeschermingsautoriteit</a>.</p>
    <p>Gratis testtoegang veroorzaakt geen automatische betalingsverplichting of verplichte einddatum. Betaalde toegang vraagt een afzonderlijke afspraak.</p>
  </main>;
}
